config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :cards
  end

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
require 'date_validator'

class Card
  include Mongoid::Document
  belongs_to :project
  field :name, type: String
  field :details, type: String
  field :dateIn, type: Date
  field :dateOut, type: Date
  field :state, type: Integer

  validates :name, length: { minimum: 3 }
  validate :expiration_date_cannot_be_in_the_past, :on => :create
  validate :dates_in_order, :on => :create

  private
    def dates_in_order
      errors.add(:dateIn, "must be before end time") unless :dateIn < :dateOut
    end

    def expiration_date_cannot_be_in_the_past
      if dateIn.present? && dateIn < Date.today
        errors.add(:Date_in, "can't be in the past")
      end
    end
end

app/models/project.rb
class Project
  include Mongoid::Document
  include ActiveModel::Validations
  has_many :cards, dependent: :destroy
  field :name, type: String
  field :state, type: Integer

  validates :name, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::RoutingError, :with => :render_not_found

  private
  def render_not_found
    render_error_page_for(404)
  end

  def render_error_page_for(code)
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/#{code}.html", :status => code, :layout => false }
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    redirect_to root_path
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    @project = Project.find(params[:project_id])
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @project = Project.find(params[:project_id])
    @card = @project.cards.create(set_params)
    if @card.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    if params[:Nstate] == "0" or params[:Nstate] == "1" or params[:Nstate] == "2"
      @card.state = params[:Nstate]
      @card.update
      redirect_to project_path(@project)
    else
      set_params_object
      if @card.valid?
        @project.cards.update(set_params)
        redirect_to project_path(@project)
      else
        render 'edit'
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    redirect_to project_path(@project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @project = Project.find(params[:project_id])
      @card = @project.cards.find(params[:id])
    end

    def set_params
      params = {}

      params["dateIn"] = Time.utc(card_params["dateIn(1i)"],
                                  card_params["dateIn(2i)"],
                                  card_params["dateIn(3i)"],
                                  23, 59, 59).in_time_zone("Bogota").to_json
      params["dateOut"] = Time.utc(card_params["dateOut(1i)"],
                                   card_params["dateOut(2i)"],
                                   card_params["dateOut(3i)"],
                                   23, 59, 59).in_time_zone("Bogota").to_json

      params["name"] = card_params[:name]
      params["details"] = card_params[:details]
      params["state"] = card_params[:state]
      params
    end

    def set_params_object
      @card.dateIn = Time.utc(card_params["dateIn(1i)"],
                                  card_params["dateIn(2i)"],
                                  card_params["dateIn(3i)"],
                                  23, 59, 59).in_time_zone("Bogota")
      @card.dateOut = Time.utc(card_params["dateOut(1i)"],
                                   card_params["dateOut(2i)"],
                                   card_params["dateOut(3i)"],
                                   23, 59, 59).in_time_zone("Bogota").to_json

      @card.name = card_params[:name]
      @card.details = card_params[:details]
      @card.state = card_params[:state]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :details, :dateIn, :dateOut, :state, :Nstate)
    end
end

app/controllers/error_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render :status => 404
  end

  def internal_error
    render :status => 500
  end

  def unacceptable
    render :status => 422
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/cards/_card.html.erb
<h4><%= card.name %></h4>

<% unless locals[:show] %>
    <p>
        <strong>Details:</strong>
        <%= card.details %>
    </p>
<% end %>

<div class="date-card">
    <p class="date-card-in">
        <%= card.dateIn %>
    </p>

    <p class="date-card-out">
        <%= card.dateOut %>
    </p>
</div>

<% unless locals[:show] %>
    <p>
        <strong>State:</strong>
        <%= card.state %>
    </p>
<% end %>

<p>
    <%= linkx_to 'Editar', edit_project_card_path(card.project, card) %> |
    <%= link_to 'Ver', [card.project, card] %>
</p>

<p>
    <%= link_to 'Borrar Tarjeta', [card.project, card],
    method: :delete, data: { confirm: '¿ Estas Seguro ?'} %>
</p>

app/views/cards/_form.html.erb
<%= form_for [@project, @card] do |form| %>
    <% if @card.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

            <ul>
                <% @card.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
      <%= form.label :dateIn %>
      <div class="date_inline">
          <%= form.date_select :dateIn, :class => "date_inline" %>
      </div>
  </div>

  <div class="field">
      <%= form.label :dateOut %>
      <div class="date_inline">
          <%= form.date_select :dateOut, :class => "date_inline" %>
      </div>
  </div>

  <div class="field">
      <%= form.select(:state, [['To Do', 0], ['Doing', 1], ['Done', 2] ]) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/_mini-card.html.erb
<%= link_to [locals[:card].project, locals[:card]], :class => "content_card" do %>
    <h4 class="title_card"><%= locals[:card].name %></h4>
    <div class="date_card">
        <p class="date_card_in">
            <%= locals[:card].dateIn %>
        </p>

        <p class="date_card_out">
            <%= locals[:card].dateOut %>
        </p>
    </div>

    <div class="bar_buttons">
        <% if locals[:card].state == 0 %>
            <%= link_to 'Doing', project_card_path(locals[:card].project, locals[:card],
                                                   "Nstate": 1), method: :patch,
                                                   :class => "link_bar execute-project middle_bar_letter" %>
            <%= link_to 'Done', project_card_path(locals[:card].project, locals[:card],
                                                  "Nstate": 2), method: :patch,
                                                  :class => "link_bar archived_project middle_bar_letter" %>
        <% end %>
        <% if locals[:card].state == 1 %>
            <%= link_to 'To Do', project_card_path(locals[:card].project, locals[:card],
                                                   "Nstate": 0), method: :patch,
                                                   :class => "link_bar edit_color middle_bar_letter" %>
            <%= link_to 'Done', project_card_path(locals[:card].project, locals[:card],
                                                  "Nstate": 2), method: :patch,
                                                  :class => "link_bar archived_project middle_bar_letter" %>
        <% end %>
        <% if locals[:card].state == 2 %>
            <%= link_to 'To Do', project_card_path(locals[:card].project, locals[:card],
                                                   "Nstate": 0), method: :patch,
                                                   :class => "link_bar edit_color middle_bar_letter" %>
            <%= link_to 'Doing', project_card_path(locals[:card].project, locals[:card],
                                                   "Nstate": 1), method: :patch,
                                                   :class => "link_bar execute-project middle_bar_letter" %>
        <% end %>
    </div>
<% end %>

app/views/cards/edit.html.erb
<div class="content">
    <h1>Editing Card</h1>
    <div class="button_bar_content">
        <%= link_to 'Back', project_path(@project), :class => "link_bar back_color" %>
        <%= link_to 'Show', project_card_path(@project, @card), :class => "link_bar show_color" %>
    </div>

    <%= render 'form'%>
</div>

app/views/cards/index.html.erb
cartas

app/views/cards/new.html.erb
<div class="content">
    <h1>New Card</h1>

    <%= link_to 'Back', project_path(@project), :class => "button_content" %>

    <%= render 'form' %>
</div>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content data">
    <h1><%= @card.name %></h1>

    <div class="details_card">
        <strong>Details:</strong>
        <div class="details_box">
            <%= @card.details %>
        </div>
    </div>

    <div class="date_card">
        <strong>Date Start:</strong>
        <%= @card.dateIn %>
    </div>

    <div class="date_card">
        <strong>Date End:</strong>
        <%= @card.dateOut %>
    </div>

    <div class="state_card">
        <strong>State:</strong>
        <% if @card.state == 0 %>
            To Do
        <% end %>
        <% if @card.state == 1 %>
            Doing
        <% end %>
        <% if @card.state == 2 %>
            Done
        <% end %>
    </div>

    <div class="bar_buttons button_bar_content">
        <% if @card.state == 0 %>
            <%= link_to 'Doing', project_card_path(@card.project, @card,
                                                   "Nstate": 1), method: :patch,
                                                   :class => "link_bar execute-project" %>
            <%= link_to 'Done', project_card_path(@card.project, @card,
                                                  "Nstate": 2), method: :patch,
                                                  :class => "link_bar archived_project" %>
        <% end %>
        <% if @card.state == 1 %>
            <%= link_to 'To Do', project_card_path(@card.project, @card,
                                                   "Nstate": 0), method: :patch,
                                                   :class => "link_bar edit_color" %>
            <%= link_to 'Done', project_card_path(@card.project, @card,
                                                  "Nstate": 2), method: :patch,
                                                  :class => "link_bar archived_project" %>
        <% end %>
        <% if @card.state == 2 %>
            <%= link_to 'To Do', project_card_path(@card.project, @card,
                                                   "Nstate": 0), method: :patch,
                                                   :class => "link_bar edit_color" %>
            <%= link_to 'Doing', project_card_path(@card.project, @card,
                                                   "Nstate": 1), method: :patch,
                                                   :class => "link_bar execute-project" %>
        <% end %>
    </div>

    <div class="button_bar_content">
        <%= link_to 'Back', project_path(@project), :class => "link_bar back_color"%>
        <%= link_to 'Edit', edit_project_card_path(@project, @card), :class => "link_bar edit_color" %>
        <%= link_to 'Delete', project_card_path(@project, @card), method: :delete, data: { confirm: 'Are you sure?' },
        :class => "link_bar delete_color" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <title>To Do Management</title>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/errors.html.erb
ERROR

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
    <% if project.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

            <ul>
                <% project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <label>State</label>
        <%= form.select(:state, [['Executing', 0], ['Archived', 1], ['Finish', 2] ]) %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<%= link_to project do %>

    <h2><%= project.name %></h2>

    <p>
        <% if project.state == 0 %>
            Executing
        <% end %>
        <% if project.state == 1 %>
            Archived
        <% end %>
        <% if project.state == 2 %>
            Finish
        <% end %>
    </p>
<% end %>
<div class="bar_buttons">
    <%= link_to edit_project_path(project), :class => "link_bar left_border_radious edit_color" do %>
        Edit
    <% end %>
    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link_bar right_border_radious delete_color" do %>
        Delete
    <% end  %>
</div>

app/views/projects/edit.html.erb
<div class="content">
    <h1>Editing Project</h1>

    <div class="button_bar_content">
        <%= link_to 'Back', projects_path, :class => "link_bar back_color" %>
        <%= link_to 'Show', @project, :class => "link_bar show_color" %>
    </div>

    <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>


<div class="content">
    <div class="title_content">
        <h1>Project Manager</h1>
        <h4>Gabriel Vargas Monroy</h4>
    </div>
    <%= link_to 'New Project', new_project_path, :class => "button_content" %>
</div>

<div class="content">
    <% @projects.each do |project| %>
        <% if project.state == 0 %>
            <div class="content_project execute_project">
                <%= render project %>
            </div>
        <% end %>
        <% if project.state == 1 %>
            <div class="content_project archived_project">
                <%= render project %>
            </div>
        <% end %>
        <% if project.state == 2 %>
            <div class="content_project finish_project">
                <%= render project %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/projects/new.html.erb
<div class="content">
    <h1>New Project</h1>

    <%= link_to 'Back', projects_path, :class => "button_content" %>

    <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content content_bar">
    <div class="title_content">
        <h1><%= @project.name %></h1>
        <h4>
            <% if @project.state == 0 %>
                Executing
            <% end %>
            <% if @project.state == 1 %>
                Archived
            <% end %>
            <% if @project.state == 2 %>
                Finish
            <% end %>
        </h4>
    </div>
    <div class="button_content button_bar_content">
        <%= link_to projects_path, :class => "link_bar back_color" do%>
            Back
        <% end %>
        <%= link_to edit_project_path(@project), :class => "link_bar edit_color" do %>
            Edit
        <% end %>
        <%= link_to @project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link_bar delete_color" do %>
            Delete
        <% end  %>
    </div>
    <%= link_to 'New Card', new_project_card_path(@project), :class => "button_content top_margin_button" %>
</div>

<div class="content content_bar lists">
    <div class="box_card todo_box">
        <h3>TO DO</h3>
        <% @project.cards.each do |card| %>
            <% if card.state == 0 %>
                <div class="card">
                    <%= render 'cards/mini-card', locals: {card: card} %>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class="box_card doing_box">
        <h3>DOING</h3>
        <% @project.cards.each do |card| %>
            <% if card.state == 1 %>
                <div class="card">
                    <%= render 'cards/mini-card', locals: {card: card} %>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class="box_card done_box">
        <h3>DONE</h3>
        <% @project.cards.each do |card| %>
            <% if card.state == 2 %>
                <div class="card">
                    <%= render 'cards/mini-card', locals: {card: card} %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>